urbanet_user_homepage:
    pattern:  /login
    defaults: { _controller: FOSUserBundle:Security:login }
    
urbanet_user_register:
    pattern:  /inscription
    defaults: { _controller: FOSUserBundle:Registration:register }
