<?php

namespace Urbanet\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnTantQueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnTantQueRepository extends EntityRepository
{
}
