urbanet_media:
    resource: "@UrbanetMediaBundle/Resources/config/routing.yml"
    prefix:   /

urbanet_annonce:
    resource: "@UrbanetAnnonceBundle/Resources/config/routing.yml"
    prefix:   /

urbanet_event:
    resource: "@UrbanetEventBundle/Resources/config/routing.yml"
    prefix:   /

urbanet_cv:
    resource: "@UrbanetCvBundle/Resources/config/routing.yml"
    prefix:   /

urbanet_main:
    resource: "@UrbanetMainBundle/Resources/config/routing.yml"
    prefix:   /

#The bundles developped in this project
urbanet_user:
    resource: "@UrbanetUserBundle/Resources/config/routing.yml"
    prefix:   /

#SonataMediaBundle
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

#SonataUserBundle Link between FOSUser and SonataAdmin
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

#FosUserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
 
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
 
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
 
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
 
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
#FosFacebookBundle
#_security_check:
#  pattern:  /login_check
#_security_logout:
#  pattern:  /logout
    
# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal