<?php

namespace Urbanet\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppartientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppartientRepository extends EntityRepository
{
}
