<?php

namespace Urbanet\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
* DisciplineRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class DisciplineRepository extends EntityRepository
{
}