<?php

namespace Urbanet\AnnonceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
* AnnonceRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class AnnonceRepository extends EntityRepository
{
}