<?php

namespace Urbanet\AnnonceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryPubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryPubRepository extends EntityRepository
{
}
