<?php

namespace Training\AnnonceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstimerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstimerRepository extends EntityRepository
{
}
