<?php

namespace Urbanet\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MediathequeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediathequeRepository extends EntityRepository
{
}
