<?php

namespace Training\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CrewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrewRepository extends EntityRepository
{
}
