<?php

namespace Urbanet\CvBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
* CVArtRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class CVArtRepository extends EntityRepository
{
}