<?php

namespace Urbanet\CvBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvaluerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluerRepository extends EntityRepository
{
}
