<?php

namespace Urbanet\CvBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpectacleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpectacleRepository extends EntityRepository
{
}
